---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tenant.kubesphere.io.ks.cloud.cmft
  resources:
  - workspacetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenant.kubesphere.io.ks.cloud.cmft
  resources:
  - workspacetemplates/finalizers
  verbs:
  - update
- apiGroups:
  - tenant.kubesphere.io.ks.cloud.cmft
  resources:
  - workspacetemplates/status
  verbs:
  - get
  - patch
  - update
